<a href="https://colab.research.google.com/github/theeduazizjon-cell/ai_engin_prac/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
#checking pandas version

print(pd.__version__)

2.2.3

In [ ]:
mydataset ={
    'cars': ["BMW", "VOLVO", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

print(mydataset)
print("======")

df = pd.DataFrame(mydataset)
print(df)

{'cars': ['BMW', 'VOLVO', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'], 'counts': [3, 7, 2, 8, 1, 9, 3]}
======
      cars  counts
0      BMW       3
1    VOLVO       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
#head() -> default reads first 5 variables from the start from 0 till 4

df.head()

      cars  counts
0      BMW       3
1    VOLVO       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [ ]:
#tail() -> default reads 5 rows from the bottom

df.tail()

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
#columns - property
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
#shape - properties

df.shape

(7, 2)

In [ ]:
#dtypes - property

df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
#describe() -> method , describes only numberical columns

df.describe() #include="all" -> argument

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [ ]:
#iloc -> method that prints out the N positioned value in the df

df.iloc[0]

cars      BMW
counts      3
Name: 0, dtype: object

In [ ]:
#loc - method , first argument should be the number of the rows and the second one is the for the coloumn name

df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

Conditional selecting process or filtering

In [ ]:
df[df["counts"] > 3]

    cars  counts
1  VOLVO       7
3  Tesla       8
5   Ford       9

In [ ]:
#mean() prints the mean number isnide of the df

df.mean(numeric_only=True)

counts    4.714286
dtype: float64

In [ ]:
#sum() -> method to get the sum of the df

df.sum()

In [ ]:
#min and #max -> methods to get the min or max value in the df

df.min()
df.max()

cars      VOLVO
counts        9
dtype: object

In [ ]:
#median -> method that gets the median

df.median(numeric_only=True)

In [ ]:
#count -> method that measures the counts

df.count()

cars      7
counts    7
dtype: int64

In [ ]:
#std -> standard daviation n

df.std(numeric_only=True)

Methods that are widely used for cleaning the data

In [ ]:
data_with_missing = {
    'cars': ["BMW", "Volvo", None, "Tesla", "Ferrari", None,"Ford"],
    'counts': [3, 7, None, 8,1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
#prints out the numbers that are null or missing

df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [ ]:
#dropna -> method that ignores the row which's got missing valued rows and prints everything except that row

df_missing.dropna(how="all")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
# deletes the column where even value is missing
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [ ]:
# fillna() -> fills the values where they are missed
df_missing.fillna("unknown")

      cars   counts
0      BMW      3.0
1    Volvo      7.0
2  unknown  unknown
3    Tesla      8.0
4  Ferrari      1.0
5  unknown      9.0
6     Ford  unknown

In [33]:
from google.colab import files
uploaded = files.upload()   # opens a file picker

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

In [35]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
# how to read excel and jason files

#df = pd.read_excel("Titanic-Dataset.xlsx")
#df = pd.read_json("Titanic-Dataset.json")

In [ ]:
#helps to export the file in the format we want it

df.to_excel("output.xslx")

Series --> 1D

In [36]:
cars = pd.Series(["BMW", "Tesla", "Ferrari"])

print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [37]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']